name: Upload Artifacts to Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Clean build directory (unix)
        if: matrix.os != 'windows-latest'
        run: rm -rf build/ci

      - name: Clean build directory (windows)
        if: matrix.os == 'windows-latest'
        run: if (Test-Path "build/ci") { Remove-Item -Recurse -Force "build/ci" }

      - name: Install wayland dep in ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libwayland-dev \
          wayland-protocols \
          libxkbcommon-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure
        run: cmake --preset ci

      - name: Build
        run: cmake --build --preset ci

      - name: Install artifacts
        run: cmake --install build/ci --prefix package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.os }}
          path: package
  
  build-macos-universal:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean build directory
        run: rm -rf build/macos-universal

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure (Universal)
        run: cmake --preset macos-universal

      - name: Build (Universal)
        run: cmake --build --preset macos-universal

      - name: Package artifacts
        run: cmake --install build/macos-universal --prefix package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib-macos-universal
          path: package
  upload:
    needs: [build, build-macos-universal] 
    runs-on: ubuntu-latest 
    steps: 
      - name: Download all artifacts 
        uses: actions/download-artifact@v4 
        with: 
          path: artifacts 
      - name: Zip packages
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          cd artifacts
          if [ -d "lib-windows-latest" ]; then zip -r "GLBW-${VERSION}_WIN64.zip" "lib-windows-latest" fi
          if [ -d "lib-ubuntu-latest" ]; then zip -r "GLBW-${VERSION}_LINUX_x64.zip" "lib-ubuntu-latest" fi
          if [ -d "lib-macos-universal" ]; then zip -r "GLBW-${VERSION}_MACOS.zip" "lib-macos-universal" fi
      - name: Upload to GitHub Release 
        uses: softprops/action-gh-release@v2 
        with: 
          files: artifacts/*.zip
        env: 
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
